Description of simtb_makeTC
Home > simtb_v18 > sim > simtb_makeTC.m
simtb_makeTC
PURPOSE
simtb_makeTC() - Makes component TCs (time courses)
SYNOPSIS
function [TC, eTC, blocks, events, uevents, sP] = simtb_makeTC(sP, sub)
DESCRIPTION
 simtb_makeTC() - Makes component TCs (time courses)
                  Builds event time course based on experimental design.
                  Generates the TC based on the chosen model.
                  Normalizes the TC based on the peak-to-peak difference.
                  Adds Gaussian noise.
   Usage:
    >> [TC, eTC] = simtb_makeTC(sP, sub);
   INPUTS:
   sP            = parameter structure used in the simulations
   sub           = subject index
   OUTPUTS:
   TC            = Generated time courses
   eTC           = Event time course (prior to modeling)
   blocks        = Event time courses of each block
   events        = Event time courses of each event type
   uevents       = Event time courses for each component
   sP            = Updated parameter structure with parameters for TC models
   see also: simtb_showTC(), simtb_TCsource(), simtb_main()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_TCsource simtb_TCsource() - Contains the definitions for the generation of TCs
simtb_makeTC_block simtb_makeTC_block() - Builds task blocks
simtb_makeTC_event simtb_makeTC_event() - Builds event time courses
simtb_rand_seed simtb_rand_seed() - Set random number generator (RNG) seeds
This function is called by:
simtb_showTC simtb_showTC() - Show generation of TCs (time courses)
simtb_main simtb_main() - Main function for performing simulations