Description of simtb_makeSM
Home > simtb_v18 > sim > simtb_makeSM.m
simtb_makeSM
PURPOSE
simtb_makeSM() - Makes component SMs (spatial maps)
SYNOPSIS
function SM = simtb_makeSM(sP, sub)
DESCRIPTION
   simtb_makeSM()  - Makes component SMs (spatial maps)
                     Generates the SM.
                     Adds Gaussian noise.
   USAGE:
    >> SM = simtb_makeSM(sP, sub);
   INPUTS: (OPTIONAL)
   sP            = parameter structure used in the simulations
   sub           = index number for current running subject
   OUTPUTS:
   SM            = Generated spatial maps matrix
   see also: simtb_main(), simtb_generateSM()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_createmask simtb_createmask() - Creates data mask with ones inside the head and zeros outside.
simtb_generateSM simtb_generateSM() - Generates a SM based on definitions in simtb_SMsource()
This function is called by:
simtb_main simtb_main() - Main function for performing simulations