Description of simtb_TCsource
Home > simtb_v18 > sim > simtb_TCsource.m
simtb_TCsource
PURPOSE
simtb_TCsource() - Contains the definitions for the generation of TCs
SYNOPSIS
function [tc, MDESC, P, PDESC] = simtb_TCsource(eTC, TR, sourceType, P)
DESCRIPTION
 simtb_TCsource()  - Contains the definitions for the generation of TCs
 Usage:
  >> [tc, MDESC, P, PDESC] = simtb_TCsource(eTC, TR, sourceType);
  >> [tc, MDESC, P, PDESC] = simtb_TCsource(eTC, TR, sourceType, P);
 INPUTS:
 eTC          = [nT x 1] event vector
 TR           = repetition time (in seconds)
 sourceType   = model to use for the generation of the TC
 P            = vector of parameters for the BOLD generation model [OPTIONAL]
 OUTPUTS:
 tc      =  [nT x 1] component time course
 MDESC   =  Description of the model used
 P       =  Parameters used in model
 PDESC   =  Description of model parameters
 see also: simtb_countTCmodels()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_countTCmodels simtb_countTCmodels() - Determines the number of TC models defined in simtb_TCsource()
simtb_balloon_model simtb_balloon_model() - Nonlinear balloon model to generate TCs
simtb_spm_hrf simtb_spm_hrf() - Returns a hemodynamic response function
This function is called by:
simtb_countTCmodels simtb_countTCmodels() - Determines the number of TC models defined in simtb_TCsource()
simtb_makeTC simtb_makeTC() - Makes component TCs (time courses)