Description of simtb_main
Home > simtb_v18 > sim > simtb_main.m
simtb_main
PURPOSE
simtb_main() - Main function for performing simulations
SYNOPSIS
function simtb_main(sP)
DESCRIPTION
 simtb_main()  - Main function for performing simulations
           For each subject:
           - Generates time courses (TC) and spatial maps (SM)
           - Multiplies TC*SM and adds scaled activations to baseline (B) to make dataset (D)
           - Simulates dataset motion (OPTIONAL)
           - Adds Rician noise to dataset (OPTIONAL)
           - Saves parameters, TC, SM, dataset, motions parameters and any figures displayed.
 Usage:
  >> simtb_main(sP)
 INPUTS:
 sP        = simulation parameter structure
 OUTPUTS:
 (none, all outputs are saved to file).
 If sP.verbose_display, will display and save images of parameters and output
 see also: simtb_create_sP(), simtb_params()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_figure_model simtb_figure_model() - Shows SM contours and/or Tissue Model
simtb_figure_output simtb_figure_output() - Shows TC/SM output for a given subject
simtb_figure_params simtb_figure_params() - Shows simulation parameters
simtb_show_motion simtb_show_motion() - Shows translational/rotational motion of subjects
simtb_checkparams simtb_checkparams() - Checks for appropriate and consistent simulation parameters
simtb_makefilename simtb_makefilename() - Makes filenames for various file types
simtb_createmask simtb_createmask() - Creates data mask with ones inside the head and zeros outside.
simtb_saveMOT simtb_saveMOT() - Writes motion parameters to file
simtb_saveasnii simtb_saveasnii() - Save data matrix as an .nii file
simtb_addMotion simtb_addMotion() - Simulates motion (translation/rotation) of dataset
simtb_makeBaseline simtb_makeBaseline() - Generate baseline intensity map for each subject
simtb_makeSM simtb_makeSM() - Makes component SMs (spatial maps)
simtb_makeTC simtb_makeTC() - Makes component TCs (time courses)
simtb_rand_seed simtb_rand_seed() - Set random number generator (RNG) seeds
This function is called by: