Description of simtb_SMsource
Home > simtb_v18 > sim > simtb_SMsource.m
simtb_SMsource
PURPOSE
simtb_SMsource() - Contains the definitions of the 2-D SMs and their tissue types
SYNOPSIS
function [z,TT] = simtb_SMsource(x, y, randx, randy, randrot, sourceID)
DESCRIPTION
 simtb_SMsource()  - Contains the definitions of the 2-D SMs and their tissue types
 Usage:
  >> [z,TT] = simtb_SMsource(x, y, randx, randy, randrot, nV, sourceID);
 INPUTS:
 x         = x matrix over which z is evaluated (nV x nV, defined using meshgrid)
 y         = y matrix over which z is evaluated (nV x nV, defined using meshgrid)
 randx     = offset in x (in normalized units, [-1,1])
 randy     = offset in y (in normalized units, [-1,1])
 randrot   = rotation (in radians)
 sourceID  = ID of function to evaluate
 OUTPUTS:
 z =  nV x nV spatial map
 TT = Tissue Type [e.g., 1 = SIGNAL DROPOUT, 2 = WM, 3 = GM, 4 = CSF]
 see also: simtb_generateSM(), simtb_pickSM()
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
simtb_countSM simtb_countSM() - Determines the number of sources defined in simtb_SMsource()
simtb_countTT simtb_countTT() - Determines the number and default levels of Tissue Types
simtb_generateSM simtb_generateSM() - Generates a SM based on definitions in simtb_SMsource()