Description of simtb_create_sP
Home > simtb_v18 > sim > simtb_create_sP.m
simtb_create_sP
PURPOSE
simtb_create_sP() - Initializes parameter structure
SYNOPSIS
function SIMULATION_PARAMETERS = simtb_create_sP(param_filename, M, nC)
DESCRIPTION
   simtb_create_sP()  - Initializes parameter structure
   Usage:
    >> sP = simtb_create_sP;
    >> sP = simtb_create_sP(param_filename);
    >> sP = simtb_create_sP(param_filename, M, nC);
    >> sP = simtb_create_sP([], M, nC);
   INPUT:
   If no input       Builds parameter structure based on default values
   param_filename  = parameter filname [OPTIONAL]. If provided, parameter values
                     will be revised by definitions in param_filename.
   M               = number of subjects [OPTIONAL, default is 10].
   nC              = number of components [OPTIONAL, default is all sources]
   OUTPUT:
   sP              = parameter structure
   see also: simtb_params(), simtb_checkparams()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_countSM simtb_countSM() - Determines the number of sources defined in simtb_SMsource()
simtb_countTT simtb_countTT() - Determines the number and default levels of Tissue Types
This function is called by:
simtb_params simtb_params() - Provides information on all simulation parameters
simtb simtb() - Initializes the simtb GUI