Description of simtb_makeBaseline
Home > simtb_v18 > sim > simtb_makeBaseline.m
simtb_makeBaseline
PURPOSE
simtb_makeBaseline() - Generate baseline intensity map for each subject
SYNOPSIS
function Baseline = simtb_makeBaseline(sP, sub)
DESCRIPTION
 simtb_makeBaseline()  - Generate baseline intensity map for each subject
                         Based on definitions of all functions in simtb_SMsource().
 Usage:
  >> Baseline = simtb_makeBaseline(sP, sub)
 INPUTS:
  sP         = parameter structure used in the simulations
  sub        = index number for subject
 OUTPUTS:
 Baseline    = nV x nV spatial map of the signal intensity for selected subject
 see also: simtb_generateSM(), simtb_SMsource()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_createmask simtb_createmask() - Creates data mask with ones inside the head and zeros outside.
simtb_generateSM simtb_generateSM() - Generates a SM based on definitions in simtb_SMsource()
This function is called by:
simtb_figure_model simtb_figure_model() - Shows SM contours and/or Tissue Model
simtb_main simtb_main() - Main function for performing simulations