Description of simtb_generateSM
Home > simtb_v18 > sim > simtb_generateSM.m
simtb_generateSM
PURPOSE
simtb_generateSM() - Generates a SM based on definitions in simtb_SMsource()
SYNOPSIS
function [SM,TT] = simtb_generateSM(sourceID, nV, offset_x, offset_y, theta, spread)
DESCRIPTION
 simtb_generateSM()  - Generates a SM based on definitions in simtb_SMsource()
 Usage:
  >> [SM,TT] = simtb_generateSM(sourceID, nV);
  >> [SM,TT] = simtb_generateSM(sourceID, nV, offset_x, offset_y, theta, spread);
 INPUTS:
 sourceID   = ID of source to generate
 nV         = number of 1-D voxels; image will be nV x nV
 offset_x   = offset in x (in pixels) [OPTIONAL, default = 0]
 offset_y   = offset in y (in pixels) [OPTIONAL, default = 0]
 theta      = rotation in degrees [OPTIONAL, default = 0]
 spread     = spatial magnification factor [OPTIONAL, default = 1]
 OUTPUTS:
 SM         = nV x nV spatial mapindices of the selected spatial map
 TT         = Tissue Type of SM [e.g., 1 = SIGNAL DROPUT, 2 = WM, 3 = GM, 4 = CSF]
 see also: simtb_SMsource()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_SMsource simtb_SMsource() - Contains the definitions of the 2-D SMs and their tissue types
This function is called by:
simtb_figure_drawSMs simtb_figure_drawSMs() - Shows contours for all defined SMs
simtb_makeBaseline simtb_makeBaseline() - Generate baseline intensity map for each subject
simtb_makeSM simtb_makeSM() - Makes component SMs (spatial maps)