Description of simtb_createmask
Home > simtb_v18 > io > simtb_createmask.m
simtb_createmask
PURPOSE
simtb_createmask() - Creates data mask with ones inside the head and zeros outside.
SYNOPSIS
function MASK = simtb_createmask(sP, saveMASKasNIFTI)
DESCRIPTION
 simtb_createmask()  - Creates data mask with ones inside the head and zeros outside.
                Note that this utility should NOT be used to determine
                a mask if motion is simulated since the head boundaries will move.
 Usage:
  >> MASK = simtb_createmask(sP, saveMASKasNIFTI);
 INPUTS:
 sP               = simulation parameter structure
 saveMASKasNIFTI  = FLAG to save MASK as a NIFTI file
 OUTPUTS:
 MASK             = MASK of ones where data are defined and zero elsewhere
CROSS-REFERENCE INFORMATION
This function calls:
simtb_makefilename simtb_makefilename() - Makes filenames for various file types
simtb_saveasnii simtb_saveasnii() - Save data matrix as an .nii file
This function is called by:
simtb_main simtb_main() - Main function for performing simulations
simtb_makeBaseline simtb_makeBaseline() - Generate baseline intensity map for each subject
simtb_makeSM simtb_makeSM() - Makes component SMs (spatial maps)