Description of simtb_figure_drawSMs
Home > simtb_v18 > display > simtb_figure_drawSMs.m
simtb_figure_drawSMs
PURPOSE
simtb_figure_drawSMs() - Shows contours for all defined SMs
SYNOPSIS
function [CH, CMAP] = simtb_figure_drawSMs(H, nV, contour_level, sP, sub)
DESCRIPTION
 simtb_figure_drawSMs() - Shows contours for all defined SMs
 Usage:
  >> [CH, CMAP] = simtb_figure_drawSMs;
  >> [CH, CMAP] = simtb_figure_drawSMs(H, nV, contour_level)
  >> [CH, CMAP] = simtb_figure_drawSMs(H, nV, contour_level, sP, sub)
 INPUTS:
 H             = axis handle [OPTIONAL, default = gca]
 nV            = number of 1-D voxels; image will be nV x nV [OPTIONAL, default = 256]
 contour_level = level at which to draw contours [OPTIONAL, default = 0.5]
 sP            = parameter structure [OPTIONAL, but required if sub is defined]
 sub           = subject index [OPTIONAL]
 OUTPUTS:
 CH            = children figure handles
 CMAP          = colormap
   see also: simtb_pickSM(), simtb_pickedSM()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_countSM simtb_countSM() - Determines the number of sources defined in simtb_SMsource()
simtb_generateSM simtb_generateSM() - Generates a SM based on definitions in simtb_SMsource()
This function is called by:
simtb_figure_pickedSM simtb_figure_pickedSM() - Draws and fills SM contours for selected sources
simtb_pickSM simtb_pickSM() - GUI for selecting sources