Description of simtb_figure_output
Home > simtb_v18 > display > simtb_figure_output.m
simtb_figure_output
PURPOSE
simtb_figure_output() - Shows TC/SM output for a given subject
SYNOPSIS
function [cmTC, cmSM, comp_figure] = simtb_figure_output(sP, sub, TC, SM, plotit)
DESCRIPTION
 simtb_figure_output() - Shows TC/SM output for a given subject
   Usage:
    >> [cmTC, cmSM, comp_figure] = simtb_figure_output(sP, sub, TC, SM, plotit);
    >> [cmTC, cmSM, comp_figure] = simtb_figure_output(sP, sub, [], [], plotit);
    >> [cmTC, cmSM, comp_figure] = simtb_figure_output(sP, sub);
   INPUTS:
   sP            = parameter structure used in the simulations
   sub           = subject index
   TC            = component TCs for subject, size [nT, nC]; leave empty to load from file
   SM            = component SMs for subject, size [nC, nV*nV]; leave empty to load from file
   plotit        = 0|1 to create figure
   OUTPUTS:
   cmTC          = correlation matrix of TC
   cmSM          = correlation matrix of SM
   comp_figure   = figure handle
   see also: simtb_makeTC(), simtb_TCsource()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_group_getSM simtb_group_getSM() - Loads saved subject SMs (spatial maps)
simtb_group_getTC simtb_group_getTC() - Loads saved subject TCs (time courses)
simtb_figdimension simtb_figdimension() - Computes position of figure given desired aspect ratio and scale
simtb_returnFileIndex simtb_returnFileIndex() - Returns the file index for naming
This function is called by:
simtb_main simtb_main() - Main function for performing simulations