Description of simtb_lighten_color
Home > simtb_v18 > display > simtb_lighten_color.m
simtb_lighten_color
PURPOSE
simtb_lighten_color() - Lightens color (reduces saturation)
SYNOPSIS
function lighter = simtb_lighten_color(rgbvalue, saturation)
DESCRIPTION
   simtb_lighten_color() - Lightens color (reduces saturation)
                           Converts RGB to HSV,
                           Reduces saturation,
                           Converts HSV back to RGB
   USAGE:
    >> lighter = simtb_lighten_color(rgbvalue, saturation);
   INPUTS: (OPTIONAL)
   rgbvalue      = rgb color to lighten
   saturation    = desired fraction of saturation [1 = original, 0 = white]
   OUTPUTS:
   lighter       = lightened rgb color
   see also: simtb_figure_pickSM(), simtb_showSMCountours()
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
simtb_figure_pickedSM simtb_figure_pickedSM() - Draws and fills SM contours for selected sources
simtb_pickSM simtb_pickSM() - GUI for selecting sources
simtb_showSMContours simtb_showSMContours() - Plot SMs as contours