Description of simtb_figure_params
Home > simtb_v18 > display > simtb_figure_params.m
simtb_figure_params
PURPOSE
simtb_figure_params() - Shows simulation parameters
SYNOPSIS
function param_figures = simtb_figure_params(sP, paramlistin)
DESCRIPTION
 simtb_figure_params()  - Shows simulation parameters
 USAGE:
 >> param_figures = simtb_figure_params(sP, paramlistin)
 INPUTS:
 sP             = parameter structure
 paramlistin    = cell array of parameters to display. [OPTIONAL, default = all]
                  Accepted parameters:
                 'SM_present',        'SM_translate_x',
                 'SM_translate_y',    'SM_theta'
                 'SM_spread',         'D_baseline'
                 'D_CNR',             'D_pSC'
                 'D_motion_deviates', 'TC_block_amp'
                 'TC_event_amp',      'TC_unique_amp'
 OUTPUTS:
 param_figures   = figure handles
 see also: simtb_main()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_figdimension simtb_figdimension() - Computes position of figure given desired aspect ratio and scale
simtb_pcolor simtb_pcolor() - Produces pcolor-like images of data matrices
This function is called by:
simtb_main simtb_main() - Main function for performing simulations