Description of simtb_figure_model
Home > simtb_v18 > display > simtb_figure_model.m
simtb_figure_model
PURPOSE
simtb_figure_model() - Shows SM contours and/or Tissue Model
SYNOPSIS
function model_figure = simtb_figure_model(sP, sub, contour_level, WhichPanels)
DESCRIPTION
 simtb_figure_model() - Shows SM contours and/or Tissue Model
 USAGE:
 >> model_figure = simtb_figure_model(sP, sub, contour_level, WhichPanel)
 INPUTS:
 sP             = parameter structure
 sub            = subject index [OPTIONAL, default = 1]
 contour_level  = level at which to draw contours [OPTIONAL, default = 0.5]
 WhichPanels    = Type of data to plot, 1 = Map of Sources; 2 = Tissue Type Model;
                  [OPTIONAL, default is both([1,2])]
 OUTPUTS:
 model_figure   = figure handle
   see also: simtb_main()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_figdimension simtb_figdimension() - Computes position of figure given desired aspect ratio and scale
simtb_figure_pickedSM simtb_figure_pickedSM() - Draws and fills SM contours for selected sources
simtb_makeBaseline simtb_makeBaseline() - Generate baseline intensity map for each subject
This function is called by:
simtb_main simtb_main() - Main function for performing simulations