Description of simtb_figure_pickedSM
Home > simtb_v18 > display > simtb_figure_pickedSM.m
simtb_figure_pickedSM
PURPOSE
simtb_figure_pickedSM() - Draws and fills SM contours for selected sources
SYNOPSIS
function [CH, CMAP] = simtb_figure_pickedSM(SM_ind, H, nV, contour_level, sP, sub)
DESCRIPTION
   simtb_figure_pickedSM() - Draws and fills SM contours for selected sources
   USAGE:
    >> [CH, CMAP] = simtb_figure_pickedSM(SM_ind, H, nV, contour_level, sP, sub);
   INPUTS:
   SM_ind        = indexes of sources in SM [OPTIONAL, default = []]
   H             = figure handle [OPTIONAL, default = gca]
   nV            = number of voxels in SM [OPTIONAL, default = 256]
   contour_level = which contour to draw, smaller is lower and wider [OPTIONAL, default = 0.5]
   sP            = parameter structure used in the simulations [OPTIONAL, default = []]
   sub           = index number for current running subject [OPTIONAL, default = []]
   OUTPUTS:
   CH            = children figure handles
   CMAP          = colormap
   see also: simtb_main(), simtb_figure_model()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_figure_drawSMs simtb_figure_drawSMs() - Shows contours for all defined SMs
simtb_lighten_color simtb_lighten_color() - Lightens color (reduces saturation)
This function is called by:
simtb_figure_model simtb_figure_model() - Shows SM contours and/or Tissue Model