Description of simtb_pickSM
Home > simtb_v18 > display > simtb_pickSM.m
simtb_pickSM
PURPOSE
simtb_pickSM() - GUI for selecting sources
SYNOPSIS
function varargout = simtb_pickSM(varargin)
DESCRIPTION
 simtb_pickSM() - GUI for selecting sources
 USAGE:
 >> simtb_pickSM
 >> simtb_pickSM(SM_source_ID)
 >> SM_source_ID = simtb_pickSM;
 INPUTS:
 SM_source_ID = IDs for initial desired sources [OPTIONAL, default = [] ]
 OUTPUTS: (OPTIONAL)
 SM_source_ID = IDs for selected sources
CROSS-REFERENCE INFORMATION
This function calls:
simtb_figure_drawSMs simtb_figure_drawSMs() - Shows contours for all defined SMs
simtb_inpoly simtb_inpoly() - Tests whether a point is inside a polygon
simtb_lighten_color simtb_lighten_color() - Lightens color (reduces saturation)
This function is called by: