Description of simtb_figdimension
Home > simtb_v18 > display > simtb_figdimension.m
simtb_figdimension
PURPOSE
simtb_figdimension() - Computes position of figure given desired aspect ratio and scale
SYNOPSIS
function RECT = simtb_figdimension(aspectratio, scale, alignment)
DESCRIPTION
   simtb_figdimension() - Computes position of figure given desired aspect ratio and scale
   Usage:
    >> RECT = simtb_figdimension(aspectratio, scale, alignment);
   INPUTS: (OPTIONAL)
   aspectratio   = aspect ratio is width/height of the desired figure
   scale         = multiplicative scale, 1 leaves the same size
   alignment     = horizontal placement, vertical placement
                       'cm' = center middle
                       'lt' = left top
                       'rb' = left bottom
   OUTPUTS:
   RECT          = figure position used as figure('Position', RECT)
   see also: simtb_figure_params(), simtb_showSM()
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
simtb_figure_model simtb_figure_model() - Shows SM contours and/or Tissue Model
simtb_figure_output simtb_figure_output() - Shows TC/SM output for a given subject
simtb_figure_params simtb_figure_params() - Shows simulation parameters
simtb_showSM simtb_showSM() - Plot SMs
simtb_showSMContours simtb_showSMContours() - Plot SMs as contours
simtb_showTC simtb_showTC() - Show generation of TCs (time courses)
simtb_show_motion simtb_show_motion() - Shows translational/rotational motion of subjects