Description of simtb_params
Home > simtb_v18 > helper > simtb_params.m
simtb_params
PURPOSE
simtb_params() - Provides information on all simulation parameters
SYNOPSIS
function varargout = simtb_params(P)
DESCRIPTION
   simtb_params()  - Provides information on all simulation parameters
   Usage:
    >> SIMULATION_PARAMS = simtb_params;
    >> ALL_PARAMETERS_HELP = simtb_params('all');
    >> simtb_params(P);
    >> [PARAMETER_HELP, DESC, DTYPE, EXAMPLE, LABEL, DEFAULT] = simtb_params(P);
   INPUTS: (OPTIONAL)
   no input  =   Returns a list of simtb parameters
   'all'     =   Displays help for all parameters
   P         =   A string, displays help for any parameters with names matching P.
   OUTPUTS: (OPTIONAL)
   SIMULATION_PARAMS  = cell array with list of parameters (returned if no input)
   PARAMETER_HELP     = string, full help for parameter P [DESC, DTYPE, EXAMPLE, DEFAULT]
     DESC             = string, description of P
     DTYPE            = string, data type of P
     EXAMPLE          = string, example of how to modify P
     LABEL            = string, short description of P for GUI
     DEFAULT          = string, default value used in simtb_create_sP and GUI
   see also:  simtb_create_sP(), simtb_checkparams()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_countSM simtb_countSM() - Determines the number of sources defined in simtb_SMsource()
simtb_countTT simtb_countTT() - Determines the number and default levels of Tissue Types
simtb_create_sP simtb_create_sP() - Initializes parameter structure
This function is called by: