Description of simtb_checkparams
Home > simtb_v18 > helper > simtb_checkparams.m
simtb_checkparams
PURPOSE
simtb_checkparams() - Checks for appropriate and consistent simulation parameters
SYNOPSIS
function [errorflag, Message] = simtb_checkparams(sP, OPT)
DESCRIPTION
   simtb_checkparams()  - Checks for appropriate and consistent simulation parameters
   Usage:
    >> [errorflag, Message] = simtb_checkparams(sP)
    >> [errorflag, Message] = simtb_checkparams(sP, OPT)
   INPUTS:
   sP      = parameter strcutre
   OPT     = string designating the parameters to check [OPTIONAL, default = 'all']
             Possible values for OPT and their descriptions follow.
             'all': checks all parameters.
               '1': checks output parameters only.
               '2': checks main parameters only.
               '3': checks SM setting parameters only.
               '4': checks TC_Block parameters only.
               '5': checks TC_Event parameters only.
               '6': checks Simulating noise parameters only.
               '7': checks TC_Unique parameters only.
               '8': checks TC source parameters only.
   OUTPUTS:
   errorflag   = indicator for error inout, 0 for no error
   Message     = string with error information (if any)
   see also: simtb_create_sP(), simtb_main()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_countSM simtb_countSM() - Determines the number of sources defined in simtb_SMsource()
simtb_countTCmodels simtb_countTCmodels() - Determines the number of TC models defined in simtb_TCsource()
simtb_countTT simtb_countTT() - Determines the number and default levels of Tissue Types
This function is called by:
simtb_main simtb_main() - Main function for performing simulations