Description of simtb_countSM
Home > simtb_v18 > helper > simtb_countSM.m
simtb_countSM
PURPOSE
simtb_countSM() - Determines the number of sources defined in simtb_SMsource()
SYNOPSIS
function count = simtb_countSM
DESCRIPTION
 simtb_countSM() - Determines the number of sources defined in simtb_SMsource()
 Usage:
  >> simtb_countSM;
  >> count = simtb_countSM;
 OUTPUTS:
  count = number of SM sources defined.
 see also: simtb_SMsource()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_SMsource simtb_SMsource() - Contains the definitions of the 2-D SMs and their tissue types
This function is called by:
simtb_figure_drawSMs simtb_figure_drawSMs() - Shows contours for all defined SMs
simtb_checkparams simtb_checkparams() - Checks for appropriate and consistent simulation parameters
simtb_countTT simtb_countTT() - Determines the number and default levels of Tissue Types
simtb_params simtb_params() - Provides information on all simulation parameters
simtb_create_sP simtb_create_sP() - Initializes parameter structure