Description of simtb_countTCmodels
Home > simtb_v18 > helper > simtb_countTCmodels.m
simtb_countTCmodels
PURPOSE
simtb_countTCmodels() - Determines the number of TC models defined in simtb_TCsource()
SYNOPSIS
function varargout = simtb_countTCmodels
DESCRIPTION
 simtb_countTCmodels() - Determines the number of TC models defined in simtb_TCsource()
 Usage:
  >> simtb_countTCmodels;
  >> [count, MDESC, NPARAMS, PDESC] = simtb_countTCmodels;
 INPUTS:
  none:   uses the model definitions in simtb_TCsource()
 OUTPUTS (OPTIONAL):
  if none:   displays a description of each model and model parameters
  if output:
   count  = number of TC generation models defined in simtb_TCsource()
   MDESC  = string description of each model
   NPARAM = number of parameters required for each model
   PDESC  = string description of the parameters required for each model
 see also: simtb_TCsource()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_TCsource simtb_TCsource() - Contains the definitions for the generation of TCs
This function is called by:
simtb_checkparams simtb_checkparams() - Checks for appropriate and consistent simulation parameters
simtb_TCsource simtb_TCsource() - Contains the definitions for the generation of TCs