Description of simtb_makefilename
Home > simtb_v18 > helper > simtb_makefilename.m
simtb_makefilename
PURPOSE
simtb_makefilename() - Makes filenames for various file types
SYNOPSIS
function filename = simtb_makefilename(sP, dtype, subIND)
DESCRIPTION
   simtb_makefilename()  - Makes filenames for various file types
   Usage:
    >> filename = simtb_makefilename(sP, dtype, subIND)
    >> filename = simtb_makefilename(sP, dtype)
   INPUTS:
   sP                = parameter structure used in the simulations
   dtype             = data type to be saved. Choices:
                        {'PARAMS', 'SIM', 'DATA', 'MOT', 'MASK',
                        'model figure', 'parameter figure', 'output figure'}
   subIND (OPTIONAL) = subject index (not needed for 'PARAMS',
                                     'model figure', or 'parameter figure')
   OUTPUTS:
   filename          = filename
   see also: simtb_main()
CROSS-REFERENCE INFORMATION
This function calls:
simtb_returnFileIndex simtb_returnFileIndex() - Returns the file index for naming
This function is called by:
simtb_group_getSM simtb_group_getSM() - Loads saved subject SMs (spatial maps)
simtb_group_getTC simtb_group_getTC() - Loads saved subject TCs (time courses)
simtb_createmask simtb_createmask() - Creates data mask with ones inside the head and zeros outside.
simtb_main simtb_main() - Main function for performing simulations